GET http://localhost:8000/api/v1/cars

###

GET http://localhost:8000/api/v1/cars/656d19fc8462aaf8a7ba339a

###

POST http://localhost:8000/api/v1/cars
Content-Type: application/json

{
    "make": "Ford",
    "model": "F-150"
}

###

DELETE http://localhost:8000/api/v1/cars/656d19fc8462aaf8a7ba339a

###

PATCH http://localhost:8000/api/v1/cars/656d19fc8462aaf8a7ba339a
Content-Type: application/json

{
    "make": "Ford",
    "model": "Mustang"
}

